config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolios/:id', to: 'portfolios#destroy', as: 'delete_portfolio'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #ROOT will declare what's the root of the application
  root to: 'pages#home'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  #include Placeholder
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails, -> {where(subtitle: 'Ruby on Rails')}

  #after_initialize :set_defaults
  #def set_defaults
    #self.main_image ||= Placeholder.image_generator('600','400')
    #self.thumb_image ||= Placeholder.image_generator('350','200')
  #end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    flash.now[:notice] = "We have exactly 0 books available."
    @portf_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
  end

  def angular
    @angular_portf_items = Portfolio.angular
  end

  #Renders the view
  def new
    @portf_items = Portfolio.new
  end
  
  #Creates de item into the DB
  def create 
    @portf_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portf_items.save
        format.html{redirect_to portfolios_path, notice: "Your Portfolio has been created successfully"}
      else
        format.html { render :new }
      end
    end
  end

  #Renders the view for the specified item and puts all
  #the info inside the fields to be edited
  def edit
  end

  #Writes de changes into the DB
  def update 
    respond_to do |format|
      if @portf_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Record successfully updated" }
      else
        format.html {render :edit }
      end
    end
  end

  def show
  end

  def destroy
    #Destroy/delete the record
    @portf_items.destroy
    #Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed'}
    end
  end

  private 
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      :main_image, 
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end

  def set_portfolio_item
    #This will lookup the object i wanna distroy with the id params
    @portf_items = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img.url
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<!--"form_for" actually maps each attribute into the corresponding fields right away, for example when we want to edit fields-->
<%= form_for(@portf_items) do |f| %>
  <% if @portf_items.errors.any? %>
    <% @portf_items.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_area :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;'%>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
        
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 10 %>
      </div>
    </div>   
  </div>
    
  <hr>
  
  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |tech_form| %>
        <%= render 'technology_fields', f: tech_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>  
  </div>
<% end %>

app/views/portfolios/_portf_item.html.erb
<div class="my_name col-md-4" data-id="<%= portf_item.id %>">
  <div class="card mb-4 box-shadow" >
    <%= image_tag portfolio_img(portf_item.thumb_image, 'thumb'), width: '100%'%>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portf_item.title, portfolio_show_path(portf_item.id) %></span>
        <br>  
        <%= portf_item.subtitle %>
      </p>
      <!--<div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-muted">9 mins</small>
      </div>-->
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f%>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<!--<a href="portfolios/new">Create New Item</a>-->

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portf_items.each do |portfolio_item| %>
 <p>--------------------------------------</p>
 <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></h2>
 <p><%= portfolio_item.subtitle %></p>
 <p><%= portfolio_item.body %></p>
 <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
 <br>
 <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
 <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item.id), method: :delete, data:{confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portf_items: @portf_items%>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <% if logged_in?(:site_admin) %>
      <div class="my-4">
        <%=  link_to "New Portfolio Item", new_portfolio_path(@portf_items), class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      
      <%= render partial: 'portf_item', collection: @portf_items %>
    
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portf_items: @portf_items%>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portf_items.main_image, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portf_items.title%></h1>
      
      <em><%= @portf_items.subtitle %></em>
      <hr>
      <p><%= @portf_items.body %></p>

      <h3>Technologies Used:</h3>

      <div>
        <% @portf_items.technologies.each do |t| %>
          <p><%= t.name %></p>
        <% end %>
      </div>

      <% if logged_in?(:site_admin) %>
        <div>
          <%=  link_to "Edit Item", edit_portfolio_path(@portf_items), class: 'btn btn-warning btn-block' %>
          <%=  link_to "Delete Item", delete_portfolio_path(@portf_items), class: 'btn btn-warning btn-block' %>
        </div>
      <% end %>
    </div>
  </div>  
</div>