config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolios/:id', to: 'portfolios#destroy', as: 'delete_portfolio'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #ROOT will declare what's the root of the application
  root to: 'pages#home'

end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer" style="color:#899077"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <a class="navbar-brand text-dark" href="/"><h3>Abigail Campos</h3></a>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link text-dark', 'span' %>
      <%= login_helper 'nav-link text-dark'%>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">DevelopExp Blog</h1>
    <p class="lead blog-description">Welcome to my knowledge corner, where I share glimpses about my professional journey alongside some tutorials of what I've learned while working on different projects. Hope you find it useful and interesting.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)%>
    </span>    
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light blog-nav">
  <div class="container">
    
    <%= link_to "Abigail Campos", root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>


  </div>
</nav>


app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Hi, I'm Abigail, a software developer focused on web development; I'm also interested in interface design and project management. I like to maintain a forever student mentality too. With that in mind, be ready to take a look at my professional development through this blog.</p>
  </div>
  
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <% @side_bar_topics.each do |topic| %>      
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">

      <li><a href="https://github.com/aoihanabi"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/abigail-campos-73738b197/"><%= fa_icon "linkedin" %></a></li>
      <%# <li><a href="#"><%= fa_icon "twitter" %><%#</a></li> %>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Abi's Portfolio</h1>
    <p class="lead text-muted">Welcome to a small reflection of my learning journey as a developer, I'm passionate about helping others make their ideas come true. Here you'll find some of those projects I've adventured with.</p>
    <%#  Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely. %>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary my-2' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary my-2' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">This portfolio contains projects I've worked on with a team or solo.</p>
        <p class="text-muted">
          Here you'll be able to take a look into a variety of technologies I've explored as I discover my interests during my professional development journey. 
          If you'd like to work together don't hesitate to <a href="<%= contact_path %>">contact me</a>.
        </p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>

        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>Abigail Campos</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

<%= link_to "Home", root_path, class: 'text-white' %>
<%= link_to "About Me", about_me_path, class: 'text-white' %>
<%= link_to "Contact", contact_path, class: 'text-white' %>
<%= link_to "Blogs", blogs_path, class: 'text-white' %>
<%= link_to "Portfolio", portfolios_path, class: 'text-white' %>